<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wp_mailqueue"
 *
 * Auto generated by Extension Builder 2021-03-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Mailqueue',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Gernot Ploiner',
    'author_email' => 'gp@webprofil.at',
    'state' => 'beta',
    'clearCacheOnLoad' => true,
    'version' => '2.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0-11.5.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
